### ISSUE TITLE
[Bug]: Remote I/O Error

### ISSUE THREAD

**Issue by gabriella-martin** [crismc/rpi_i2c_oled#9]
### Requirements

- [X] I have updated RPI_I2C_OLED to the latest available version
- [X] I did a search to see if there is a similar issue.

### Current Behavior

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[13:58:51] INFO: Starting I2C OLED App...
/dev/i2c-1
[13:58:51] INFO: /dev/i2c-1 enabled
[13:58:51] INFO: I2C access enabled. Proceeding!
[13:58:51] INFO: Display Info to OLED
[13:58:51] INFO: Running 'python3 display.py  -c /data/options.json'
Traceback (most recent call last):
  File "/I2C_OLED/display.py", line 5, in <module>
    from bin.Config import Config
  File "/I2C_OLED/bin/Config.py", line 5, in <module>
    from bin.Screens import *  
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/I2C_OLED/bin/Screens.py", line 53, in <module>
    class BaseScreen:
  File "/I2C_OLED/bin/Screens.py", line 58, in BaseScreen
    def __init__(self, duration, display = Display(), utils = Utils(), config = None):
                                           ^^^^^^^^^
  File "/I2C_OLED/bin/Screens.py", line 17, in __init__
    self.clear()
  File "/I2C_OLED/bin/Screens.py", line 27, in clear
    self.display.begin()
  File "/I2C_OLED/bin/SSD1306.py", line 97, in begin
    self._initialize()
  File "/I2C_OLED/bin/SSD1306.py", line 154, in _initialize
    self.command(SSD1306_DISPLAYOFF)                    # 0xAE
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/I2C_OLED/bin/SSD1306.py", line 89, in command
    self._bus.write_byte_data(self._address, control, value)
OSError: [Errno 121] Remote I/O error
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

### Context

YAML state
```yaml

```

### Environment

```markdown
- Browser: Firefox
- HA Version:11.03
- I2C_OLED: JMDO 96 c
```

**Comment by gabriella-martin** [comment]
Could be something I am doing wrong but unsure
